Repository Team-ThinkBoo/ClubAccount-BE, pull requests merged in 2025-04, with the labels that each got.

#7 [TB-4] 영수증 등록 & 조회 API 구현
  .github/workflows/codecov.yml
  build.gradle
  src/main/java/com/ClubAccount_BE/ClubAccountBeApplication.java
  src/main/java/com/ClubAccount_BE/core/config/S3Config.java
  src/main/java/com/ClubAccount_BE/core/response/PagingResponse.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/CreateReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/CreateReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/FindReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/FindReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/request/CreateReceiptRequestDto.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/response/CreateReceiptResponseDto.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/response/FindReceiptResponseDto.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/ReceiptRepositoryAdapter.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/S3Adapter.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/persistence/entity/ReceiptEntity.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/persistence/repository/ReceiptRepository.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/in/CreateReceiptUseCase.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/in/FindReceiptUseCase.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/out/CreateReceiptPort.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/out/FindReceiptPort.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/out/UploadReceiptPort.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/CreateReceiptService.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/FindReceiptService.java
  src/main/java/com/ClubAccount_BE/receipt/domain/Receipt.java
  src/main/java/com/ClubAccount_BE/receipt/domain/type/ReceiptCategory.java
  src/main/java/com/ClubAccount_BE/receipt/mapper/ReceiptMapper.java
  src/test/java/com/ClubAccount_BE/factory/receipt/ReceiptTestFactory.java
  src/test/java/com/ClubAccount_BE/receipt/application/service/CreateReceiptServiceTest.java
  src/test/java/com/ClubAccount_BE/receipt/mapper/ReceiptMapperTest.java
Labels: refactor, feat

#9 [TB-8] Auth 커스텀 어노테이션 생성
  src/main/java/com/ClubAccount_BE/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/ClubAccount_BE/core/config/WebConfig.java
  src/main/java/com/ClubAccount_BE/core/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ClubAccount_BE/core/exception/ErrorCode.java
  src/main/java/com/ClubAccount_BE/core/exception/UnAuthorizedException.java
  src/main/java/com/ClubAccount_BE/core/meta/LoginUser.java
Labels: feat

#10 [TB-10]CI-CD: 배포 자동화 수정
  .github/workflows/dev-deploy.yml
  infra/deploy/docker-compose.yml
  infra/deploy/scripts/deploy.sh
Labels: fix

#11 [TB-11] 인증 유저 조회 방식 변경
  src/main/java/com/ClubAccount_BE/core/config/SwaggerConfig.java
  src/main/java/com/ClubAccount_BE/core/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/UserRepository.java
  src/main/java/com/ClubAccount_BE/user/application/port/in/FindUserUseCase.java
  src/main/java/com/ClubAccount_BE/user/application/port/out/FindUserPort.java
  src/main/java/com/ClubAccount_BE/user/application/service/FindUserService.java
  src/test/java/com/ClubAccount_BE/core/config/auth/LoginUserArgumentResolverTest.java
Labels: refactor

#15 [TB-13] CORS 설정에서 credentials 사용 시 origin 명시
  src/main/java/com/ClubAccount_BE/core/config/WebConfig.java
Labels: fix

#19 [TB-15] 토큰 재발급 httponly 쿠기로 변경_2
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/token/TokenApiPresentation.java
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/token/TokenController.java
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/token/dto/request/TokenRequest.java
Labels: refactor

#20 [TB-16] 이메일 인증 기능
  build.gradle
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/signin/SignInController.java
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/token/TokenController.java
  src/main/java/com/ClubAccount_BE/core/config/SecurityConfig.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/email/EmailApiPresentation.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/email/EmailController.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/email/dto/request/EmailSendRequest.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/email/dto/request/EmailVerifyRequest.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/email/dto/response/EmailVerifyResponse.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/InMemoryVerificationAdapter.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/InMemoryVerificationRepository.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/VerificationRepository.java
  src/main/java/com/ClubAccount_BE/user/application/port/in/email/EmailUseCase.java
  src/main/java/com/ClubAccount_BE/user/application/port/out/email/VerificationCodePort.java
  src/main/java/com/ClubAccount_BE/user/application/service/email/EmailService.java
Labels: feat

#22 [TB-18] 영수증 관련 DTO 유효성 검증 및 상수 클래스 추가
  src/main/java/com/ClubAccount_BE/core/constant/CommonConstant.java
  src/main/java/com/ClubAccount_BE/core/response/PagingResponse.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/CreateReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/FindReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/UpdateReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/api/CreateReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/api/FindReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/api/UpdateReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/request/ReceiptItemRequest.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/request/ReceiptRequest.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/response/ReceiptCreateResponse.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/response/ReceiptDetailResponse.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/dto/response/ReceiptResponse.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/ReceiptImageRepositoryAdapter.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/ReceiptRepositoryAdapter.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/persistence/entity/ReceiptEntity.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/in/CreateReceiptUseCase.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/in/FindReceiptUseCase.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/CreateReceiptService.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/FindReceiptService.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/UpdateReceiptService.java
  src/main/java/com/ClubAccount_BE/receipt/domain/Receipt.java
  src/main/java/com/ClubAccount_BE/receipt/domain/type/ReceiptCategory.java
  src/main/java/com/ClubAccount_BE/receipt/mapper/ReceiptMapper.java
Labels: refactor, feat, chore

#23 [TB -17] 로그아웃과 비밀번호 재설정, 비회원 조회 링크 생성
  build.gradle
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/logout/LogoutApiPresentation.java
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/logout/LogoutController.java
  src/main/java/com/ClubAccount_BE/auth/adapter/out/persistence/InMemoryDeleteRefreshTokenAdapter.java
  src/main/java/com/ClubAccount_BE/auth/adapter/out/persistence/repository/InMemoryTokenRepository.java
  src/main/java/com/ClubAccount_BE/auth/application/port/in/SignOutUseCase.java
  src/main/java/com/ClubAccount_BE/auth/application/port/out/DeleteRefreshTokenPort.java
  src/main/java/com/ClubAccount_BE/auth/application/service/SignOutService.java
  src/main/java/com/ClubAccount_BE/core/config/SecurityConfig.java
  src/main/java/com/ClubAccount_BE/core/config/WebConfig.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/signup/SignUpApi.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/signup/SignUpController.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/signup/validator/PasswordMatchValidator.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/update/PasswordResetApi.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/update/PasswordResetController.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/update/dto/request/PasswordResetRequest.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/update/dto/response/PasswordResetResponse.java
  src/main/java/com/ClubAccount_BE/user/adapter/in/update/validator/PasswordMatchValidatorForReset.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/UserRepository.java
  src/main/java/com/ClubAccount_BE/user/application/port/in/update/PasswordResetUseCase.java
  src/main/java/com/ClubAccount_BE/user/application/port/out/update/FindUserByEmailPort.java
  src/main/java/com/ClubAccount_BE/user/application/service/update/PasswordResetService.java
  src/main/java/com/ClubAccount_BE/user/application/service/update/UpdatePasswordPort.java
  src/main/java/com/ClubAccount_BE/user/domain/User.java
  src/test/java/com/ClubAccount_BE/receipt/application/service/CreateReceiptServiceTest.java
Labels: feat, chore

#24 [TB-19] 링크를 통해 접속한 비회원에 대해 영수증 조회 허용
  src/main/java/com/ClubAccount_BE/core/config/SecurityConfig.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/FindReceiptController.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/in/web/api/FindReceiptApi.java
  src/main/java/com/ClubAccount_BE/receipt/adapter/out/ReceiptRepositoryAdapter.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/in/FindReceiptUseCase.java
  src/main/java/com/ClubAccount_BE/receipt/application/port/out/FindReceiptPort.java
  src/main/java/com/ClubAccount_BE/receipt/application/service/FindReceiptService.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/UserRepository.java
  src/main/java/com/ClubAccount_BE/user/application/port/out/FindUserPort.java
Labels: refactor, feat

#26 [TB-21] 로그인시 link UUID 전달
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/signin/SignInController.java
  src/main/java/com/ClubAccount_BE/auth/adapter/in/web/signin/dto/response/TokenResponse.java
  src/main/java/com/ClubAccount_BE/auth/application/dto/SignInResult.java
  src/main/java/com/ClubAccount_BE/auth/application/port/in/SignInUseCase.java
  src/main/java/com/ClubAccount_BE/auth/application/service/SignInService.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/ClubAccount_BE/user/adapter/out/persistence/repository/UserRepository.java
  src/main/java/com/ClubAccount_BE/user/application/port/out/FindUserLinkPort.java
  src/main/java/com/ClubAccount_BE/user/domain/User.java
  src/main/java/com/ClubAccount_BE/user/mapper/UserMapper.java
Labels: fix, refactor
